/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 car.gltf -d 
Author: Urizel (https://sketchfab.com/urizel)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bottled-car-cd38a415db8a4607ab9dd3cc67d27462
Title: Bottled car
*/
import { Canvas } from "react-three-fiber";
import { OrbitControls } from "@react-three/drei";
import { useGLTF } from '@react-three/drei'

export function Model() {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <Canvas className="canvas">
      <OrbitControls enableZoom={false} />
      <ambientLight intensity={0.5} />
      <directionalLight position={[-2, 5, 2]} intensity={1} />
      <group scale={20} position={[0, 0, 0]} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, -1.5]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.BOTTLE_OUTSIDE} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.LIGHT} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.BOTTOM} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.BOTTLE_WOOD} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.BOTTLE_INSIDE} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.BASEMETAL} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.NAMEPLATE} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.GLASS_N_CHROME} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.GLASS_N_CHROME} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.INTERIOR} />
        </group>
      </group>
    </Canvas>
  )
}

useGLTF.preload('/car.gltf')
